exports.metadata =  {         fullName: 'Hawk__c',
                                  label: 'Hawk',
                            pluralLabel: 'Hawks',
                              nameField: {  type: 'Text',
                                           label: 'Name'
                              },
                       deploymentStatus: 'Deployed',
                           sharingModel: 'ReadWrite',
                   allowInChatterGroups:  true,
                             fields: [
                                       {           fullName: 'bandNumber__c',
                                                 externalId: 'true',
                                                      label: 'Band Number',
                                                     length: '12',
                                                   required: 'true',
                                                       type: 'Text',
                                                     unique: 'true' },

                                       {           fullName: 'bandFather__c',
                                                 externalId: 'false',
                                                      label: 'Father Band Number',
                                                     length: '12',
                                                   required: 'false',
                                                       type: 'Text',
                                                     unique: 'false' },

                                       {           fullName: 'bandMother__c',
                                                 externalId: 'false',
                                                      label: 'Mother Band Number',
                                                     length: '12',
                                                   required: 'false',
                                                       type: 'Text',
                                                     unique: 'false' },

                                       {           fullName: 'ownerID__c',
                                                description: 'This is the sqlite rowid of the owner',
                                                 externalId: 'false',
                                                      label: 'Owner ID',
                                                  precision: '4',
                                                   required: 'false',
                                                      scale: '0',
                                           trackFeedHistory: 'false',
                                                       type: 'Number',
                                                     unique: 'false' },

                                       {           fullName: 'breederID__c',
                                                description: 'This is the sqlite rowid of the breeder',
                                                 externalId: 'false',
                                                      label: 'Breeder ID',
                                                  precision: '4',
                                                   required: 'false',
                                                      scale: '0',
                                           trackFeedHistory: 'false',
                                                       type: 'Number',
                                                     unique: 'false' },

                                       {           fullName: 'breedInCaptivity__c',
                                               defaultValue: 'true',
                                                description: 'This checkbox replaces WB/CB select.',
                                                 externalId: 'false',
                                                      label: 'Breed in Captivity',
                                              trackTrending: 'false',
                                                       type: 'Checkbox' },

                                       {           fullName: 'originCountry__c',
                                                description: 'Country where hawk was bone',
                                                 externalId: 'false',
                                                      label: 'Born in:Country',
                                                     length: '20',
                                                   required: 'false',
                                           trackFeedHistory: 'false',
                                                       type: 'Text',
                                                     unique: 'false' },

                                         {         fullName: 'state__c',
                                                description: 'State where hawk was born',
                                                 externalId: 'false',
                                                      label: 'Born In:State',
                                                     length: '20',
                                                   required: 'false',
                                           trackFeedHistory: 'false',
                                                       type: 'Text',
                                                     unique: 'false' },

                                       {           fullName: 'locality__c',
                                                description: 'Name of region where hawk was born',
                                                 externalId: 'false',
                                                      label: 'Born in: Region',
                                                     length: '20',
                                                   required: 'false',
                                           trackFeedHistory: 'false',
                                                       type: 'Text',
                                                     unique: 'false' },

                                       {           fullName: 'yod__c',
                                                description: 'Yead of death',
                                                 externalId: 'false',
                                                      label: 'Year of Death',
                                                  precision: '4',
                                                   required: 'false',
                                                      scale: '0',
                                           trackFeedHistory: 'false',
                                                       type: 'Number',
                                                     unique: 'false' },

                                       {           fullName: 'cod__c',
                                                description: 'Cause of death',
                                                 externalId: 'false',
                                                      label: 'Cause of Death',
                                                     length: '20',
                                                   required: 'false',
                                           trackFeedHistory: 'false',
                                                       type: 'Text',
                                                     unique: 'false' },

                                       {           fullName: 'comments__c',
                                                description: 'Alt Band / comments',
                                                 externalId: 'false',
                                                      label: 'Comments',
                                                     length: '100',
                                                   required: 'false',
                                           trackFeedHistory: 'false',
                                                       type: 'Text',
                                                     unique: 'false' },

                                       {           fullName: 'weight__c',
                                                description: 'Mass in grams',
                                                 externalId: 'false',
                                                      label: 'Weight(g)',
                                                  precision: '4',
                                                   required: 'false',
                                                      scale: '0',
                                           trackFeedHistory: 'false',
                                                       type: 'Number',
                                                     unique: 'false' },

                                    {              fullName: 'seasons__c',
                                                description: 'Current number of hunting seasons accounted',
                                                 externalId: 'false',
                                                      label: '# of Seasons',
                                                  precision: '2',
                                                   required: 'false',
                                                      scale: '0',
                                           trackFeedHistory: 'false',
                                                       type: 'Number',
                                                     unique: 'false' },

                                     {             fullName: 'rabbits__c',
                                                description: 'Cummulative number of rabbits',
                                                 externalId: 'false',
                                                      label: '# rabbits',
                                                  precision: '4',
                                                   required: 'false',
                                                      scale: '0',
                                           trackFeedHistory: 'false',
                                                       type: 'Number',
                                                     unique: 'false' },

                                     {             fullName: 'hares__c',
                                                description: 'Cummulative number of hares',
                                                 externalId: 'false',
                                                      label: '# hares',
                                                  precision: '4',
                                                   required: 'false',
                                                      scale: '0',
                                           trackFeedHistory: 'false',
                                                       type: 'Number',
                                                     unique: 'false' },

                                     {             fullName: 'squirrels__c',
                                                description: 'Cummulative number of squirrels',
                                                 externalId: 'false',
                                                      label: '# squirrels',
                                                  precision: '4',
                                                   required: 'false',
                                                      scale: '0',
                                           trackFeedHistory: 'false',
                                                       type: 'Number',
                                                     unique: 'false' },

                                     {             fullName: 'upland__c',
                                                description: 'Cummulative number of upland fowl (pidgeons)',
                                                 externalId: 'false',
                                                      label: '# upland',
                                                  precision: '4',
                                                   required: 'false',
                                                      scale: '0',
                                           trackFeedHistory: 'false',
                                                       type: 'Number',
                                                     unique: 'false' },

                                             {     fullName: 'upland__c',
                                                description: 'Cummulative number of upland fowl (pidgeons)',
                                                 externalId: 'false',
                                                      label: '# upland',
                                                  precision: '4',
                                                   required: 'false',
                                                      scale: '0',
                                           trackFeedHistory: 'false',
                                                       type: 'Number',
                                                     unique: 'false' },

                                             {     fullName: 'waterfowl__c',
                                                description: 'Waterfowl (ducks)',
                                                 externalId: 'false',
                                                      label: '# Waterfowl',
                                                  precision: '4',
                                                   required: 'false',
                                                      scale: '0',
                                           trackFeedHistory: 'false',
                                                       type: 'Number',
                                                     unique: 'false' },

                                            {      fullName: 'miscCritters__c',
                                                description: 'Misc animals hunted',
                                                 externalId: 'false',
                                                      label: '# Misc',
                                                  precision: '4',
                                                   required: 'false',
                                                      scale: '0',
                                           trackFeedHistory: 'false',
                                                       type: 'Number',
                                                     unique: 'false' },

                                             {      fullName: 'bestSeason__c',
                                                 description: 'Best single season to date',
                                                  externalId: 'false',
                                                       label: 'Best Season',
                                                   precision: '4',
                                                    required: 'false',
                                                       scale: '0',
                                            trackFeedHistory: 'false',
                                                        type: 'Number',
                                                      unique: 'false' },

                                              {      fullName: 'overall__c',
                                                  description: 'Subjective overall bird rating.',
                                                   externalId: 'false',
                                                        label: 'Overall',
                                                    precision: '4',
                                                     required: 'false',
                                                        scale: '0',
                                             trackFeedHistory: 'false',
                                                         type: 'Number',
                                                       unique: 'false' },


                                               {      fullName: 'groupHunting__c',
                                                   description: 'subjective rating of group hunting',
                                                    externalId: 'false',
                                                         label: 'Group Hunting[0-5]',
                                                     precision: '4',
                                                      required: 'false',
                                                         scale: '0',
                                               trackFeedHistory: 'false',
                                                          type: 'Number',
                                                        unique: 'false' },


                                                {      fullName: 'dogs__c',
                                                    description: 'subjective rating of hunting with dogs',
                                                     externalId: 'false',
                                                          label: 'Hunting with Dogs[0-5]',
                                                      precision: '4',
                                                       required: 'false',
                                                          scale: '0',
                                               trackFeedHistory: 'false',
                                                           type: 'Number',
                                                         unique: 'false' },

                                                 {      fullName: 'followPosition__c',
                                                     description: 'follow/Position',
                                                      externalId: 'false',
                                                           label: 'followPosition[0-5]',
                                                       precision: '4',
                                                        required: 'false',
                                                           scale: '0',
                                                trackFeedHistory: 'false',
                                                            type: 'Number',
                                                          unique: 'false' },

                                                 {      fullName: 'speed__c',
                                                     description: 'Subjective rating of Hawks speed',
                                                      externalId: 'false',
                                                           label: 'Speed[0-5]',
                                                       precision: '4',
                                                        required: 'false',
                                                           scale: '0',
                                                trackFeedHistory: 'false',
                                                            type: 'Number',
                                                          unique: 'false' },

                                                 {      fullName: 'footing__c',
                                                     description: 'Subjective rating of Hawks footing',
                                                      externalId: 'false',
                                                           label: 'Footing[0-5]',
                                                       precision: '4',
                                                        required: 'false',
                                                           scale: '0',
                                                trackFeedHistory: 'false',
                                                            type: 'Number',
                                                          unique: 'false' },

                                                  {      fullName: 'persistence__c',
                                                      description: 'Subjective rating of Hawks persistence',
                                                       externalId: 'false',
                                                            label: 'persistence[0-5]',
                                                        precision: '4',
                                                         required: 'false',
                                                            scale: '0',
                                                 trackFeedHistory: 'false',
                                                             type: 'Number',
                                                           unique: 'false' }
                             ],

                     };


exports.picklists = { groupHunting : ['0 - No Data',
                                     '1 - Fights with other Hawks',
                                     '2 -',
                                     '3 - Migth fight with some individuals',
                                     '4 -',
                                     '5 - Does not fight even when provoked'],
                             dogs : ['0 - No Data',
                                     '1 - Attacks dogs',
                                     '2 -',
                                     '3 - Attacks some dogs but not others',
                                     '4 -',
                                     '5 - Has never attacked even a small dog chasing a rabbit'],
                   followPosition : ['0 - No Data',
                                     '1 - Usually out of position',
                                     '2 -',
                                     '3 - Follows Well',
                                     '4 -',
                                     '5 - Responds to Falconer'],
                            speed : ['0 - No Data',
                                     '1 - Loses ground to a rabbit',
                                     '2 -',
                                     '3 - Faster than a hare except in headwind',
                                     '4 -',
                                     '5 - Goshawk with brains'],
                          footing : ['0 - No Data','1 -','2 -','3 -','4 -','5 -'],
                      persistence : ['0 - No Data','1 - Bad','2 -','3 - Good','4 -','5 - Best'] };
